version: '3'

services:
  zookeeper:
    container_name: zookeeper_one
    image: quay.io/debezium/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    network_mode: host

  kafka:
    container_name: kafka_one
    image: quay.io/debezium/kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=172.16.5.162:2181
      - KAFKA_LISTENERS=PLAINTEXT://172.16.5.162:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.5.162:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    network_mode: host

  connect:
    container_name: debezium
    image: jdbc-debezium-connect:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=localhost:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - LD_LIBRARY_PATH=/instant_client
      - KAFKA_DEBUG=true
      - ZOOKEEPER_CONNECT=host.docker.internal:2181
      - DEBUG_SUSPEND_FLAG=n
      - JAVA_DEBUG_PORT=0.0.0.0:5005
      - KAFKA_LISTENERS=PLAINTEXT://172.16.5.162:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.5.162:9092
    network_mode: host

  kafka-ui:
    container_name: kafka-dash
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8089:8089"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 172.16.5.162:9092
      SERVER_PORT: 8089
    network_mode: host

volumes:
  kafka_data: